### ISSUE TITLE
[Bug] Unable to import local backup on macOS

### ISSUE THREAD

**Issue by JagandeepBrar** [CometTools/LunaSea#413]
**Describe the Bug**
There is currently no way to import a local filesystem backup on a macOS machine.

**Additional context**
This occurs because the `file_picker` package does not support macOS or any desktop embedding.

**Comment by aniqueta** [comment]
@JagandeepBrar I would broaden this, since there is also no way to restore / import filesystem backup on macOS. Or is something not working correctly on my system? Thanks.

**Comment by JagandeepBrar** [comment]
> @JagandeepBrar I would broaden this, since there is also no way to restore / import filesystem backup on macOS. Or is something not working correctly on my system? Thanks.

Thanks for the heads-up, I have broadened the title and description!

**Comment by JagandeepBrar** [comment]
Exporting the backup is now fixed with #428, macOS will now show the system share menu.

This can (and will) be improved with a conventional file window, but is considered fixed for now.

**Comment by aniqueta** [comment]
> Exporting the backup is now fixed with #428, macOS will now show the system share menu.
> 
> This can (and will) be improved with a conventional file window, but is considered fixed for now.

So importing won't work, right? Or should that now work too? Still getting an error with the latest macOS build v5.0.0 (50000017). Thanks.

**Comment by JagandeepBrar** [comment]
> > Exporting the backup is now fixed with #428, macOS will now show the system share menu.
> 
> > 
> 
> > This can (and will) be improved with a conventional file window, but is considered fixed for now.
> 
> 
> 
> So importing won't work, right? Or should that now work too? Still getting an error with the latest macOS build v5.0.0 (50000017). Thanks.

Importing still is not implemented, which is why the issue was renamed/remains open.
